# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
# Use a package of configuration called an orb.
orbs:
  # Declare a dependency on the welcome-orb
  welcome: circleci/welcome-orb@0.4.1
# Orchestrate or schedule a set of jobs
workflows:
  # Name the workflow "welcome"
  welcome:
    # Run the welcome/run job in its own container
    jobs:
      build:  # job's name; every .circleci/config.yml file must have a job named build
        docker:  # executor of the underlying technology
      # specify the version you desire here
      # use `-browsers` prefix for selenium tests, e.g. `3.6.1-browsers`
          - image: continuumio/anaconda3
      steps:
        - checkout
        - restore_cache: # restores saved dependency cache if the Branch key template or requirements.txt files have not changed since the previous run
          key: deps1-{{ .Branch }}-{{ checksum "myenv.yml" }}
        - run: 
          command: |
            chmod +x run.sh
            ./run.sh
        - save_cache: # special step to save dependency cache
            key: deps1-{{ .Branch }}-{{ checksum "myenv.yml" }}
            paths:
              - "venv"
        - store_artifacts:
            path: ./task_0.html
            destination: test-reports