version: 2.1

orbs:
  python: circleci/python@0.2.1

jobs:
  convert-dz1:
    executor: python/default
    steps:
      - checkout
      - python/load-cache
      - python/install-deps
      - python/save-cache
      - run:
          name: Jupyter get HTML
          command: |
            jupyter nbconvert —execute —to html Untitled.ipynb
            
      - store_artifacts:
          path: ./Untitled.html

workflows:
  main:
    jobs:
      - convert-Untitled
